#!/bin/bash

# you can find an extensive set of vagrant boxes here :
#			https://github.com/opscode/bento

case $1 in
	centos5)
		export BOX_NAME=$1
		export BOX_URI=https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
		export BOX_OS=rhel5
	;;
	centos6)
		export BOX_NAME=$1
		export BOX_URI=https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
		export BOX_OS=rhel
	;;
	precise)
		export BOX_NAME=$1
		export BOX_URI=https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
		export BOX_OS=ubuntu
	;;	
	raring)
		export BOX_NAME=$1
		export BOX_URI=https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
		export BOX_OS=ubuntu
	;;	
	*)
		echo "No box found for $1"
		echo "Usage: source ./set_os.sh [centos5|centos6|precise|raring]"
	;;
esac
